apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: production
type: Opaque
stringData:
  # Database Configuration
  DATABASE_URL: "postgresql://postgres:change-this-secure-password@your-rds-endpoint:5432/nextjs_fastapi"
  
  # Application Secrets
  SECRET_KEY: "change-this-to-a-secure-secret-key"
  
  # Email Configuration (optional)
  SMTP_SERVER: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USERNAME: "your-email@gmail.com"
  SMTP_PASSWORD: "your-app-password"
  
  # Redis Configuration (if using Redis)
  REDIS_URL: "redis://redis-service:6379"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production
data:
  # Environment configuration
  ENVIRONMENT: "production"
  
  # Application configuration
  BACKEND_CORS_ORIGINS: '["http://localhost:3000", "https://your-domain.com"]'
  
  # Database configuration (non-sensitive)
  DATABASE_NAME: "nextjs_fastapi"
  DATABASE_HOST: "your-rds-endpoint"
  DATABASE_PORT: "5432"